title: Hyde
email: ivelininqvorov@abv.bg
description: This is scary, but awesome!
destination: docs
baseurl: ""
# baseurl: "/paco-corp"
url: "" 
twitter_username: ivelin
github_username:  ivelin-web

exclude: [_assets, node_modules, Gemfile, Gemfile.look, gulpfile.js, package.json, package-lock.json, README.markdown]

# Build settings
plugins:
  - jekyll-feed

